---
- name: Installer et configurer un serveur DNS (Bind9)
  hosts: dns
  become: yes

  vars:
    dns_ip: "10.0.1.3"
    domain_name: "intra.local"
    network: "10.0.1"
    server_netmask: "255.255.255.0"

  tasks:

  - name: Installer Bind9 et ses dépendances
    apt:
      name:
        - bind9
        - bind9utils
        - bind9-doc
      state: present
      update_cache: yes

  - name: Configurer named.conf.options
    copy:
      dest: /etc/bind/named.conf.options
      content: |
        options {
            directory "/var/cache/bind";

            recursion yes;
            allow-recursion { any; };

            forwarders {
              1.1.1.1;
              8.8.8.8;
            };

            listen-on { {{ dns_ip }}; };
            listen-on-v6 { none; };

            dnssec-validation auto;
        };
    notify: restart bind9

  - name: Configurer les zones DNS locales
    copy:
      dest: /etc/bind/named.conf.local
      content: |
        zone "{{ domain_name }}" {
          type master;
          file "/etc/bind/db.{{ domain_name }}";
        };

        zone "{{ network.split('.')[2] }}.{{ network.split('.')[1] }}.{{ network.split('.')[0] }}.in-addr.arpa" {
          type master;
          file "/etc/bind/db.{{ network }}.rev";
        };
    notify: restart bind9

  - name: Créer la zone directe
    copy:
      dest: /etc/bind/db.{{ domain_name }}
      content: |
        $TTL 604800
        @   IN  SOA dns.{{ domain_name }}. admin.{{ domain_name }}. (
                1
                604800
                86400
                2419200
                604800 )

        @               IN  NS      dns.{{ domain_name }}.

        dns             IN  A       {{ dns_ip }}
        dhcp            IN  A       10.0.1.2
        app             IN  A       10.0.1.4
        proxy           IN  A       10.0.1.5
    notify: restart bind9

  - name: Créer la zone reverse
    copy:
      dest: /etc/bind/db.{{ network }}.rev
      content: |
        $TTL 604800
        @   IN  SOA dns.{{ domain_name }}. admin.{{ domain_name }}. (
                1
                604800
                86400
                2419200
                604800 )

        @       IN  NS    dns.{{ domain_name }}.

        3       IN  PTR   dns.{{ domain_name }}.
        2       IN  PTR   dhcp.{{ domain_name }}.
        4       IN  PTR   app.{{ domain_name }}.
        5       IN  PTR   proxy.{{ domain_name }}.
    notify: restart bind9

  - name: Activer et lancer Bind9
    systemd:
      name: bind9
      state: started
      enabled: yes

  handlers:
    - name: restart bind9
      systemd:
        name: bind9
        state: restarted
