---
- name: installation du service Nginx
  hosts: reverse
  become: true

  vars:
    apache_host: 10.0.1.4
    apache_port: 80

  tasks:
     - name: cache APT Update
       apt:
         update_cache: yes
         cache_valid_time: 3600

     - name: installer nginx
       apt:
          name: nginx
          state: present

     - name: deployer la configuration reverse proxy
       template:
         src: templates/ReverseProxy.conf.j2
         dest: /etc/nginx/sites-available/reverse-proxy.conf
         mode: '0644'
       notify: redemarrer Nginx

     - name: activer le reverse proxy
       file:
        src: /etc/nginx/sites-available/reverse-proxy.conf
        dest: /etc/nginx/sites-enabled/reverse-proxy.conf
        state: link
        force: yes
       notify: redemarrer Nginx
     - name: desactiver le site par defaut
       file:
         path: /etc/nginx/sites-enabled/default
         state: absent
       notify: redemarrer nginx


     - name: demarrer nginx
       ansible.builtin.systemd_service:
         name: nginx.service
         state: started
         enabled: true
