---
- name: Installer et configurer un serveur DHCP (ISC DHCPD)
  hosts: dhcp
  become: yes

  vars:
    dhcp_interface: "ens33"
    server_ip: "10.0.1.2"
    server_netmask: "255.255.255.0"
    dhcp_network: "10.0.0.0"
    dhcp_broadcast: "10.0.0.255"
    dhcp_range_start: "10.0.0.100"
    dhcp_range_end: "10.0.0.200"
    dhcp_router: "10.0.1.254"
    dns_servers: "10.0.1.3"

  tasks:

  - name: Installer le paquet ISC DHCP Server
    apt:
      name: isc-dhcp-server
      state: present
      update_cache: yes

  - name: Configurer l’interface utilisée par DHCP
    copy:
      dest: /etc/default/isc-dhcp-server
      content: |
        INTERFACESv4="{{ dhcp_interface }}"
        INTERFACESv6=""
    notify: restart dhcp

  - name: Créer la configuration dhcpd.conf
    copy:
      dest: /etc/dhcp/dhcpd.conf
      content: |
        default-lease-time 600;
        max-lease-time 7200;
        authoritative;

        option domain-name-servers {{ dns_servers }};

        subnet {{ dhcp_network }} netmask {{ server_netmask }} {
          range {{ dhcp_range_start }} {{ dhcp_range_end }};
          option routers {{ dhcp_router }};
          option broadcast-address {{ dhcp_broadcast }};
        }
    notify: restart dhcp

  - name: S’assurer que le service DHCP est activé et lancé
    systemd:
      name: isc-dhcp-server
      state: started
      enabled: yes

  handlers:
    - name: restart dhcp
      systemd:
        name: isc-dhcp-server
        state: restarted